<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Leave</name>
   <tag></tag>
   <elementGuidId>bde7cdf2-e9ec-4762-be6b-8a54ce85c27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/web/index.php/leave/viewLeaveModule']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-main-menu-item--name ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/web\/index\.php\/leave\/viewLeaveModule&quot;] .oxd-main-menu-item--name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Leave&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e0a880b-eacd-4002-a9a8-66d735be1bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-text oxd-text--span oxd-main-menu-item--name</value>
      <webElementGuid>155e4d61-2dcc-4d71-8285-ba2eea16f0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave</value>
      <webElementGuid>14c41c37-5760-4624-a1a9-a441e305ca9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-90519252a00e508009fd06b5ebfdc672</value>
      <webElementGuid>c6a343a0-82f5-429e-8192-f4620f231e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/web/index.php/leave/viewLeaveModule']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-main-menu-item--name ')]</value>
      <webElementGuid>e0f70b82-a962-4987-9f44-f316c60eddb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/web/index.php/leave/viewLeaveModule']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' oxd-main-menu-item--name ')]</value>
      <webElementGuid>7a940f86-c91c-4e77-933c-a4e09bf4e2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Leave' or . = 'Leave')]</value>
      <webElementGuid>87ccb4f8-6bdb-4d4b-8add-5deb1240c0ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
